# Generated by Django 6.0.6 on 2026-06-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_directiva', models.CharField(max_length=100)),
                ('cargo_directiva', models.CharField(max_length=100)),
                ('presupuesto_directiva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='presupuesto')),
                ('num_integrantes', models.IntegerField()),
            ],
        ),
    ]
