# Generated by Django 4.2.30 on 2026-06-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100)),
                ('precio_materia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('creditos_materia', models.IntegerField()),
                ('num_estudiantes_materia', models.IntegerField()),
            ],
        ),
    ]
