# Generated by Django 6.0.6 on 2026-06-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(max_length=100)),
                ('sueldo_profesor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='sueldo')),
                ('curso_profesor', models.IntegerField()),
            ],
        ),
    ]
